## Basic Configuration
baseurl = "https://shyamjos.com/"
languageCode = "en"
title = "Shyam Jos"
theme = "hyde-hyde"

## Hugo Built-in Features
#.Site.Config.Services.Disqus.Shortname = "shyamjos"
enableRobotsTXT = true
summarylength = 0
enableEmoji=true

[Permalinks]
	post = "/:filename"


## Site Settings
[params]
    title = "Shyam Jos" 
    author = "Shyam Jos"
    description = "Random Bits From A DevOps Engineer"
    authorimage = "/assets/img/shyam_jos_photo.jpeg"
    dateformat = "2 Jan 2006"

    # sidebar, copyright & license
    copyright = "Shyam Jos"
    showBuiltWith = false

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    #Other options
    relatedPosts= true
    postNavigation = false

## Meta Tags
[params.meta]
    description = "Hey I am Shyam Jos. Welcome to my personal blog, where I write about Linux, DevOps, Cloud and Automation."
    keywords = "DevOps,linux,cloud,automation,sysadmin,blog"
    

## Social Accounts
[params.social]
    github = "shyamjos"
    linkedin = "shyamjos"
    twitter = "shyamjose"
    stackoverflow = "2460764"
    email = "shyamjosepp+website@gmail.com"

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"


[outputs]
  home = ['html', 'rss']
  section = ['html']
  taxonomy = ['html']
  term = ['html']


